# https://zellwk.com/blog/github-actions-deploy/
name: deploy new version
on:
  push:
    branches: [ main ]
jobs:
  deploy-new-version:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: run deploy script
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} /app/pylumber-ui/deploy_new_version.sh